apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dice-app-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: dice-app
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s