alertmanager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false

prometheus:
  enabled: true
grafana:
  enabled: true