name: Build, Test and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Maven project
        run: mvn clean package -DskipTests=false
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker image tag
        run: echo "TAG=git_${GITHUB_SHA::5}" >> $GITHUB_ENV     
      - name: Build & Tag Docker image
        run: |
          docker build -t docker-dice -f Dockerfile .
          docker tag docker-dice dima01211/practice:${TAG}
      - name: Push Docker image
        run: |
          docker push dima01211/practice:${TAG}
