name: Build, Test and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project
        run: mvn clean package -DskipTests=false

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set Docker image tag
        run: echo "TAG=git_${GITHUB_SHA::5}" >> $GITHUB_ENV

      - name: Build & Tag Docker image
        run: |
          docker build -t docker-dice -f Dockerfile .
          docker tag docker-dice us-central1-docker.pkg.dev/maximal-totem-469711-d7/practice:${TAG}

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/maximal-totem-469711-d7/practice:${TAG}
